name: iiot-portal

services:
  portal:
    image: nginx:alpine
    container_name: daq_portal
    restart: unless-stopped
    ports:
      - "${PORTAL_PORT:-8080}:80"
    volumes:
      - ../../services/portal:/usr/share/nginx/html:ro
