#!/usr/bin/env bash
#
# A wizard walks a human through a manual procedure, step by step.
# Generated by the /wizard skill.
#
# Everything above the "STAGES" marker is the wizard library: do not hand-edit
# it. Author the per-step stages below the marker.

set -euo pipefail

# ──────────────────────────────────────────────────────────────────────────
# Wizard library: delightful, consistent UX, identical across every wizard.
# ──────────────────────────────────────────────────────────────────────────

if [[ -t 1 ]] && command -v tput >/dev/null 2>&1 && [[ "$(tput colors 2>/dev/null || echo 0)" -ge 8 ]]; then
  BOLD=$(tput bold); DIM=$(tput dim); RESET=$(tput sgr0)
  BLUE=$(tput setaf 4); GREEN=$(tput setaf 2); YELLOW=$(tput setaf 3); RED=$(tput setaf 1)
else
  BOLD=""; DIM=""; RESET=""; BLUE=""; GREEN=""; YELLOW=""; RED=""
fi

# Author sets this at the top of the stages section.
TOTAL_STAGES=0

_STAGE_INDEX=0
ENV_FILE="${ENV_FILE:-.env}"
WRITTEN_ENV=()    # KEYs written to ENV_FILE this run
WRITTEN_SECRET=() # secret NAMEs set this run
SKIPPED=()        # things we couldn't do (e.g. gh missing)

# _clear wipes the terminal so only the current step is on screen. No-op when
# output isn't a terminal, so piped logs stay readable.
_clear() {
  [[ -t 1 ]] || return 0
  if command -v tput >/dev/null 2>&1; then tput clear; else printf '\033[2J\033[3J\033[H'; fi
}

# banner "Title" shows the opening frame: what this wizard does.
banner() {
  _clear
  printf '\n%s%s  %s%s\n' "$BOLD" "$BLUE" "$1" "$RESET"
  printf '%s  %s stages%s\n\n' "$DIM" "$TOTAL_STAGES" "$RESET"
  printf '%s  You drive the browser; this wizard tells you exactly what to do and\n' "$DIM"
  printf '  captures the values you copy back. Stop any time with Ctrl-C and re-run\n'
  printf '  later, since it remembers values already saved.%s\n' "$RESET"
  pause "Ready to start?"
}

# stage "Name" clears the screen, then announces a stage and shows progress.
# Clearing keeps only the current step on screen.
stage() {
  _clear
  _STAGE_INDEX=$((_STAGE_INDEX + 1))
  printf '\n%s%s▸ Stage %s/%s · %s%s\n' \
    "$BOLD" "$BLUE" "$_STAGE_INDEX" "$TOTAL_STAGES" "$1" "$RESET"
}

# say "..." prints a plain instruction line.
say()  { printf '  %s\n' "$1"; }
# step "..." is a numbered-feeling action the human takes in the browser.
step() { printf '  %s•%s %s\n' "$BLUE" "$RESET" "$1"; }
note() { printf '  %s%s%s\n' "$DIM" "$1" "$RESET"; }
warn() { printf '  %s⚠ %s%s\n' "$YELLOW" "$1" "$RESET"; }

# open_url URL opens it in the human's browser, cross-platform incl. WSL.
open_url() {
  local url="$1"
  printf '  %s↗ opening%s %s\n' "$GREEN" "$RESET" "$url"
  { if   command -v wslview     >/dev/null 2>&1; then wslview "$url"
    elif command -v explorer.exe >/dev/null 2>&1; then explorer.exe "$url"
    elif command -v xdg-open    >/dev/null 2>&1; then xdg-open "$url"
    elif command -v open        >/dev/null 2>&1; then open "$url"
    else warn "couldn't open a browser; visit it manually: $url"; fi
  } >/dev/null 2>&1 || warn "couldn't open a browser, so visit it manually: $url"
}

# pause "msg" waits for the human to confirm they've done the manual part.
pause() {
  printf '  %s%s%s ' "$DIM" "${1:-Press Enter to continue}" "$RESET"
  read -r _ || true
}

# confirm "question" is a y/N gate; returns success on yes.
confirm() {
  local reply=""
  printf '  %s? %s [y/N] ' "$YELLOW" "$1"
  read -r reply || true
  [[ "$reply" =~ ^[Yy] ]]
}

# _existing KEY: current value of KEY in ENV_FILE, if any.
_existing() {
  [[ -f "$ENV_FILE" ]] || return 1
  local line; line=$(grep -E "^${1}=" "$ENV_FILE" | tail -n1) || return 1
  printf '%s' "${line#*=}"
}

# ask KEY "Prompt" reads a value into $KEY. Offers the existing .env value as
# a default on re-runs (Enter keeps it). Visible input (non-secret).
ask() {
  local key="$1" prompt="$2" current input
  current=$(_existing "$key" || true)
  if [[ -n "$current" ]]; then
    printf '  %s%s%s %s[Enter keeps current: %s]%s ' "$BOLD" "$prompt" "$RESET" "$DIM" "$current" "$RESET"
  else
    printf '  %s%s%s ' "$BOLD" "$prompt" "$RESET"
  fi
  read -r input || true
  [[ -z "$input" && -n "$current" ]] && input="$current"
  printf -v "$key" '%s' "$input"
}

# ask_secret KEY "Prompt" is like ask, but input is hidden.
ask_secret() {
  local key="$1" prompt="$2" current input
  current=$(_existing "$key" || true)
  if [[ -n "$current" ]]; then
    printf '  %s%s%s %s[Enter keeps current]%s ' "$BOLD" "$prompt" "$RESET" "$DIM" "$RESET"
  else
    printf '  %s%s%s ' "$BOLD" "$prompt" "$RESET"
  fi
  read -rs input || true
  printf '\n'
  [[ -z "$input" && -n "$current" ]] && input="$current"
  printf -v "$key" '%s' "$input"
}

# write_env KEY VALUE upserts KEY=VALUE into ENV_FILE (creates it; replaces
# any existing line). Idempotent.
write_env() {
  local key="$1" value="$2" tmp
  touch "$ENV_FILE"
  tmp=$(mktemp)
  grep -vE "^${key}=" "$ENV_FILE" > "$tmp" || true
  printf '%s=%s\n' "$key" "$value" >> "$tmp"
  mv "$tmp" "$ENV_FILE"
  WRITTEN_ENV+=("$key")
  printf '  %s✓ wrote%s %s → %s\n' "$GREEN" "$RESET" "$key" "$ENV_FILE"
}

# set_secret NAME VALUE sets a GitHub Actions repo secret via gh. Falls back
# to a warning (and records it) if gh is unavailable or unauthenticated.
set_secret() {
  local name="$1" value="$2"
  if command -v gh >/dev/null 2>&1 && gh auth status >/dev/null 2>&1; then
    if printf '%s' "$value" | gh secret set "$name" >/dev/null 2>&1; then
      WRITTEN_SECRET+=("$name")
      printf '  %s✓ set%s GitHub secret %s\n' "$GREEN" "$RESET" "$name"
      return
    fi
  fi
  SKIPPED+=("GitHub secret $name (set it manually: gh secret set $name)")
  warn "skipped GitHub secret $name: gh not ready; set it later"
}

# set_var NAME VALUE sets a GitHub Actions repo variable (non-secret).
set_var() {
  local name="$1" value="$2"
  if command -v gh >/dev/null 2>&1 && gh auth status >/dev/null 2>&1; then
    if gh variable set "$name" --body "$value" >/dev/null 2>&1; then
      printf '  %s✓ set%s GitHub variable %s\n' "$GREEN" "$RESET" "$name"
      return
    fi
  fi
  SKIPPED+=("GitHub variable $name")
  warn "skipped GitHub variable $name, gh not ready; set it later"
}

# finish clears, then shows a closing summary of everything configured.
finish() {
  _clear
  printf '\n%s%s  ✓ Setup complete%s\n' "$BOLD" "$GREEN" "$RESET"
  (( ${#WRITTEN_ENV[@]} ))    && note "wrote ${#WRITTEN_ENV[@]} value(s) to $ENV_FILE: ${WRITTEN_ENV[*]}"
  (( ${#WRITTEN_SECRET[@]} )) && note "set ${#WRITTEN_SECRET[@]} GitHub secret(s): ${WRITTEN_SECRET[*]}"
  if (( ${#SKIPPED[@]} )); then
    printf '\n'; warn "still to do by hand:"
    for s in "${SKIPPED[@]}"; do note "  - $s"; done
  fi
  printf '\n'
}

# ──────────────────────────────────────────────────────────────────────────
# STAGES: author this section. One stage() per step the human takes.
# Replace the example below. Set TOTAL_STAGES to match the stages you write.
# ──────────────────────────────────────────────────────────────────────────

TOTAL_STAGES=6

SCRIPT_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"
PROJECT_ROOT="$(cd "$SCRIPT_DIR/.." && pwd)"
DAQ_CONFIG_JSON="$PROJECT_ROOT/services/daq_navi/config.json"

# ── Shared Detection Helpers ─────────────────────────────────────────────

detect_os() {
  OS_NAME="Linux"
  OS_ID="unknown"
  OS_VERSION=""
  if [[ -f /etc/os-release ]]; then
    # shellcheck disable=SC1091
    . /etc/os-release
    OS_NAME="${NAME:-Linux}"
    OS_ID="${ID:-unknown}"
    OS_VERSION="${VERSION_ID:-}"
  fi
  KERNEL_VER="$(uname -r)"
  ARCH="$(uname -m)"
}

detect_pci_card() {
  PCI_CARD_DETECTED=false
  PCI_DEVICE_INFO=""
  if command -v lspci >/dev/null 2>&1; then
    PCI_DEVICE_INFO="$(lspci -nn 2>/dev/null | grep -iE '13fe|advantech|1716' || true)"
    if [[ -n "$PCI_DEVICE_INFO" ]]; then
      PCI_CARD_DETECTED=true
    fi
  fi
}

detect_driver() {
  DRIVER_INSTALLED=false
  MODULE_LOADED=false
  if [[ -f /usr/lib/libbiodaq.so || -f /opt/advantech/libs/libbiodaq.so || -f /usr/local/lib/libbiodaq.so ]]; then
    DRIVER_INSTALLED=true
  fi
  if lsmod 2>/dev/null | grep -qiE 'bdaq|adv|pci1716'; then
    MODULE_LOADED=true
  fi
}

get_compose_cmd() {
  if docker compose version >/dev/null 2>&1; then
    echo "docker compose"
  elif command -v docker-compose >/dev/null 2>&1; then
    echo "docker-compose"
  else
    echo ""
  fi
}

CHECK_ONLY=false
for arg in "${@:-}"; do
  case "$arg" in
    --check-only|--check)
      CHECK_ONLY=true
      ;;
    -h|--help)
      echo "Usage: $0 [--check-only]"
      echo "  --check-only   Inspect system prerequisites non-interactively without prompting"
      exit 0
      ;;
  esac
done

# Non-interactive prerequisite check function
run_check_only() {
  printf '\n%s%s=== DAQ Navi Production Setup Prerequisite Check ===%s\n\n' "$BOLD" "$BLUE" "$RESET"

  # 1. OS & Kernel Check
  detect_os
  printf '  • OS Distribution : %s (ID: %s)\n' "$OS_NAME" "$OS_ID"
  printf '  • Kernel Version  : %s\n' "$KERNEL_VER"

  if [[ "$OS_ID" =~ ^(ubuntu|debian|linuxmint|pop)$ ]]; then
    printf '    %s✓ Supported Linux distribution detected (Ubuntu/Debian family)%s\n' "$GREEN" "$RESET"
  else
    printf '    %s⚠ Non-Ubuntu/Debian distribution detected: %s. Advantech drivers target Ubuntu/Debian/RHEL.%s\n' "$YELLOW" "$OS_ID" "$RESET"
  fi

  # 2. PCI Card Check
  printf '\n  • PCI Card Detection (Advantech PCI-1716):\n'
  detect_pci_card
  if [[ "$PCI_CARD_DETECTED" == "true" ]]; then
    printf '    %s✓ Found PCI-1716 hardware:%s\n      %s\n' "$GREEN" "$RESET" "$PCI_DEVICE_INFO"
  else
    printf '    %s⚠ PCI-1716 card not detected on PCI bus (lspci)%s\n' "$YELLOW" "$RESET"
  fi

  # 3. DAQNavi Driver Check
  printf '\n  • Advantech DAQNavi Driver & Libraries:\n'
  detect_driver
  if [[ "$DRIVER_INSTALLED" == "true" ]]; then
    printf '    %s✓ DAQNavi shared library (libbiodaq.so) is installed%s\n' "$GREEN" "$RESET"
    if [[ "$MODULE_LOADED" == "true" ]]; then
      printf '    %s✓ Kernel module loaded in active kernel%s\n' "$GREEN" "$RESET"
    else
      printf '    %s⚠ DAQNavi kernel module not currently loaded in lsmod%s\n' "$YELLOW" "$RESET"
    fi
    if [[ -x /opt/advantech/tools/dev_enum ]]; then
      local enum_out
      enum_out="$(/opt/advantech/tools/dev_enum 2>/dev/null || true)"
      printf '    %s✓ Device enumeration (dev_enum):%s\n%s\n' "$GREEN" "$RESET" "$enum_out"
    fi
  else
    printf '    %s⚠ DAQNavi library (libbiodaq.so) not found in system paths%s\n' "$YELLOW" "$RESET"
  fi

  # 4. Docker & Compose Check
  printf '\n  • Container Runtime (Docker & Docker Compose):\n'
  if command -v docker >/dev/null 2>&1; then
    local docker_ver
    docker_ver="$(docker --version 2>/dev/null || echo 'installed')"
    printf '    %s✓ Docker installed: %s%s\n' "$GREEN" "$docker_ver" "$RESET"
    local compose_bin
    compose_bin="$(get_compose_cmd)"
    if [[ -n "$compose_bin" ]]; then
      printf '    %s✓ Docker Compose available (%s)%s\n' "$GREEN" "$compose_bin" "$RESET"
    else
      printf '    %s⚠ Docker Compose not detected%s\n' "$YELLOW" "$RESET"
    fi
  else
    printf '    %s⚠ Docker is not installed%s\n' "$YELLOW" "$RESET"
  fi

  printf '\n%sPrerequisite Check complete.%s\n\n' "$BOLD" "$RESET"
  exit 0
}

if [[ "$CHECK_ONLY" == "true" ]]; then
  run_check_only
fi

# ══════════════════════════════════════════════════════════════════════════
# INTERACTIVE PRODUCTION SETUP WIZARD
# ══════════════════════════════════════════════════════════════════════════

banner "DAQ Navi Production Setup Wizard"

# ── Stage 1: OS and Kernel Verification ──────────────────────────────────
stage "System & Kernel Prerequisites"
say "Verifying host operating system and kernel version for DAQNavi compatibility."

detect_os

say "Detected Operating System: $OS_NAME ($OS_ID $OS_VERSION)"
say "Detected Kernel Version  : $KERNEL_VER ($ARCH)"

if [[ "$ARCH" != "x86_64" ]]; then
  warn "Architecture is $ARCH. Advantech DAQNavi Linux binary drivers require x86_64."
fi

if [[ "$OS_ID" =~ ^(ubuntu|debian|linuxmint|pop)$ ]]; then
  say "✓ Supported distribution: Ubuntu/Debian ecosystem."
else
  warn "Advantech DAQNavi drivers officially target Ubuntu, Debian, or RHEL/CentOS."
  note "If running on another distribution, you may need manual driver compilation."
fi

say "Checking development compilation tools and kernel headers..."
MISSING_PKGS=()
command -v gcc >/dev/null 2>&1 || MISSING_PKGS+=("build-essential")
command -v make >/dev/null 2>&1 || MISSING_PKGS+=("make")
if [[ ! -d "/lib/modules/$KERNEL_VER/build" && ! -d "/usr/src/linux-headers-$KERNEL_VER" ]]; then
  MISSING_PKGS+=("linux-headers-$KERNEL_VER")
fi

if (( ${#MISSING_PKGS[@]} )); then
  warn "Missing required kernel compilation packages: ${MISSING_PKGS[*]}"
  say "Recovery step: install the packages using apt-get:"
  note "  sudo apt-get update && sudo apt-get install -y ${MISSING_PKGS[*]}"
  if confirm "Install missing compilation packages now via sudo apt-get?"; then
    sudo apt-get update && sudo apt-get install -y "${MISSING_PKGS[@]}"
  else
    warn "Skipped package installation. Driver installation may fail without kernel headers."
  fi
else
  say "✓ Kernel headers and build tools are present."
fi
pause "Stage 1 finished. Press Enter to proceed to hardware scan."

# ── Stage 2: PCI Hardware Card Detection ──────────────────────────────────
stage "PCI Hardware Card Detection"
say "Scanning PCI expansion bus for Advantech PCI-1716 multifunction DAQ card."

detect_pci_card

if [[ "$PCI_CARD_DETECTED" == "true" ]]; then
  say "✓ Advantech PCI DAQ card detected on PCI bus:"
  note "  $PCI_DEVICE_INFO"
else
  warn "Advantech PCI-1716 card was NOT detected on the PCI bus!"
  say "Physical & BIOS Recovery Steps:"
  step "1. Power down the machine safely and disconnect main power."
  step "2. Open chassis and confirm the PCI-1716 card is fully seated in a PCI/PCIe slot."
  step "3. Ensure card bracket screw is securely fastened to chassis ground."
  step "4. Boot into motherboard BIOS/UEFI: ensure PCI expansion slots and bus clocks are enabled."
  step "5. If running inside a Virtual Machine, configure PCI Passthrough (VT-d / IOMMU) on host."
  
  if ! confirm "Proceed without physical hardware (simulate with MOCKUP_MODE=true)?"; then
    warn "Please inspect hardware installation and re-run this setup wizard."
    exit 1
  fi
fi
pause "Stage 2 finished. Press Enter to proceed to DAQNavi driver verification."

# ── Stage 3: Advantech DAQNavi Driver Installation ────────────────────────
stage "Advantech DAQNavi Driver & SDK"
say "Checking Advantech DAQNavi runtime libraries and kernel module."

detect_driver

if [[ "$DRIVER_INSTALLED" == "true" ]]; then
  say "✓ Advantech DAQNavi libraries found on system (/usr/lib/libbiodaq.so)."
  if [[ "$MODULE_LOADED" == "true" ]]; then
    say "✓ DAQNavi kernel module verified loaded via lsmod."
  else
    note "Note: DAQNavi kernel module not yet observed in lsmod. Running dev_enum will auto-load on demand."
  fi
  if [[ -x /opt/advantech/tools/dev_enum ]]; then
    say "Enumerating connected DAQ devices:"
    /opt/advantech/tools/dev_enum || true
  fi
else
  warn "Advantech DAQNavi driver was NOT detected on this machine."
  say "Advantech DAQNavi Linux Driver installation options:"
  step "1. Download the official Advantech DAQNavi Linux Drivers SDK package:"
  note "   https://www.advantech.com/en/support/details/driver?id=1-13E0I2"
  if confirm "Open Advantech driver support page in browser?"; then
    open_url "https://www.advantech.com/en/support/details/driver?id=1-13E0I2"
  fi
  step "2. Install driver package depending on package type:"
  note "   • Debian/Ubuntu (.deb) : sudo dpkg -i daqnavi_*.deb"
  note "   • RHEL/CentOS (.rpm)   : sudo rpm -ivh daqnavi_*.rpm"
  note "   • Self-extracting (.run): sudo ./linux_driver_source_*.run silent install pci1716"
  step "3. Verify kernel module load:"
  note "   lsmod | grep -iE 'bdaq|adv|pci1716'"
  step "4. Grant hardware node permissions to the current user:"
  note "   sudo usermod -aG dialout,plugdev $USER"
  step "5. Test device recognition: /opt/advantech/tools/dev_enum"
  
  if confirm "Has the driver installation been completed now?"; then
    detect_driver
    if [[ "$DRIVER_INSTALLED" == "true" ]]; then
      say "✓ Driver verified successfully!"
    else
      warn "libbiodaq.so still not detected. Continuing with mockup mode fallback available."
    fi
  else
    note "Continuing wizard. Note: physical DAQ stream will require drivers before production run."
  fi
fi

# Ensure user permissions for dialout/plugdev
if ! groups 2>/dev/null | grep -qE '\b(dialout|plugdev)\b'; then
  say "Ensuring local user has access to serial/hardware device nodes (/dev)..."
  if confirm "Add $USER to dialout and plugdev groups now?"; then
    sudo usermod -aG dialout,plugdev "$USER" || true
    say "✓ Added $USER to dialout,plugdev groups."
  fi
fi
pause "Stage 3 finished. Press Enter to proceed to Docker container runtime."

# ── Stage 4: Docker & Docker Compose Setup ────────────────────────────────
stage "Docker & Docker Compose Runtime"
say "Verifying container orchestration prerequisites for production stack."

COMPOSE_BIN="$(get_compose_cmd)"
DOCKER_READY=false
if command -v docker >/dev/null 2>&1; then
  say "✓ Docker CLI is installed: $(docker --version)"
  if [[ -n "$COMPOSE_BIN" ]]; then
    say "✓ Docker Compose is installed: $COMPOSE_BIN"
    DOCKER_READY=true
  else
    warn "Docker Compose is missing."
  fi
else
  warn "Docker is not installed on this system."
fi

if [[ "$DOCKER_READY" != "true" ]]; then
  say "Installation procedure for Docker Engine & Compose on Ubuntu/Debian:"
  note "  curl -fsSL https://get.docker.com -o get-docker.sh && sudo sh get-docker.sh"
  note "  sudo apt-get install -y docker-compose-v2"
  if confirm "Install Docker and Docker Compose automatically now?"; then
    curl -fsSL https://get.docker.com -o /tmp/get-docker.sh
    sudo sh /tmp/get-docker.sh
    sudo apt-get update && sudo apt-get install -y docker-compose-v2 || true
    COMPOSE_BIN="$(get_compose_cmd)"
    [[ -n "$COMPOSE_BIN" ]] && DOCKER_READY=true
  else
    warn "Docker not installed. Full stack launch in Stage 6 will not be possible."
  fi
fi

# Check Docker socket access
if command -v docker >/dev/null 2>&1; then
  if ! docker info >/dev/null 2>&1; then
    warn "Cannot communicate with Docker daemon without root privileges."
    say "To permit non-root Docker usage: sudo usermod -aG docker $USER"
    if confirm "Add $USER to docker group now?"; then
      sudo usermod -aG docker "$USER" || true
      note "Note: you may need to run 'newgrp docker' or re-login for group change to take effect."
    fi
  else
    say "✓ Docker daemon accessible."
  fi
fi
pause "Stage 4 finished. Press Enter to proceed to configuration customization."

# ── Stage 5: Configuration Customization (config.json & .env) ──────────────
stage "Configuration Customization"
say "Customizing DAQ Navi acquisition parameters, database host, and credentials."

DETECTED_DESC="PCI-1716,BID#0"
if [[ -x /opt/advantech/tools/dev_enum ]]; then
  PARSED_DESC="$(/opt/advantech/tools/dev_enum 2>/dev/null | grep -i 'PCI-1716' | awk -F'|' '{print $4}' | tr -d ' ' || true)"
  if [[ -n "$PARSED_DESC" ]]; then
    DETECTED_DESC="$PARSED_DESC"
  fi
fi

DEFAULT_MOCKUP="false"
if [[ "$PCI_CARD_DETECTED" != "true" ]]; then
  DEFAULT_MOCKUP="true"
fi

ask DEVICE_DESCRIPTION "Device Description [$DETECTED_DESC]:"
DEVICE_DESCRIPTION="${DEVICE_DESCRIPTION:-$DETECTED_DESC}"

ask DEVICE_ID "Device Identifier tag [pci1716-0]:"
DEVICE_ID="${DEVICE_ID:-pci1716-0}"

ask CHANNEL_COUNT "Active Analog Input Channels [4]:"
CHANNEL_COUNT="${CHANNEL_COUNT:-4}"

ask CLOCK_RATE "Sampling Clock Rate in Hz [2000]:"
CLOCK_RATE="${CLOCK_RATE:-2000}"

ask DESTINATION "Telemetry Destination (postgresql|mqtt|influxdb) [postgresql]:"
DESTINATION="${DESTINATION:-postgresql}"

ask DB_HOST "TimescaleDB / PostgreSQL Hostname [localhost]:"
DB_HOST="${DB_HOST:-localhost}"

ask DB_PORT "TimescaleDB / PostgreSQL Port [5432]:"
DB_PORT="${DB_PORT:-5432}"

ask POSTGRES_USER "TimescaleDB / PostgreSQL Username [admin]:"
POSTGRES_USER="${POSTGRES_USER:-admin}"

ask_secret POSTGRES_PASSWORD "TimescaleDB / PostgreSQL Password [admin]:"
POSTGRES_PASSWORD="${POSTGRES_PASSWORD:-admin}"

ask POSTGRES_DB "TimescaleDB Database Name [daq_db]:"
POSTGRES_DB="${POSTGRES_DB:-daq_db}"

ask MOCKUP_MODE "Run in Mockup Mode (true/false) [$DEFAULT_MOCKUP]:"
MOCKUP_MODE="${MOCKUP_MODE:-$DEFAULT_MOCKUP}"

# Write to .env
say "Writing environment variables to $ENV_FILE..."
write_env "DEVICE_DESCRIPTION" "$DEVICE_DESCRIPTION"
write_env "DEVICE_ID" "$DEVICE_ID"
write_env "CHANNEL_COUNT" "$CHANNEL_COUNT"
write_env "CLOCK_RATE" "$CLOCK_RATE"
write_env "DESTINATION" "$DESTINATION"
write_env "DB_HOST" "$DB_HOST"
write_env "DB_PORT" "$DB_PORT"
write_env "POSTGRES_USER" "$POSTGRES_USER"
write_env "POSTGRES_PASSWORD" "$POSTGRES_PASSWORD"
write_env "POSTGRES_DB" "$POSTGRES_DB"
write_env "MOCKUP_MODE" "$MOCKUP_MODE"

# Sync parameters safely with services/daq_navi/config.json via argv
if [[ -f "$DAQ_CONFIG_JSON" ]]; then
  say "Updating $DAQ_CONFIG_JSON with configured parameters..."
  python3 -c "
import sys, json

(config_path, dev_desc, dev_id, ch_count, clock_rate, dest,
 db_host, db_port, db_user, db_pass, db_name, mockup_str) = sys.argv[1:13]

with open(config_path, 'r') as f:
    cfg = json.load(f)

cfg['DEVICE_DESCRIPTION'] = dev_desc
cfg['DEVICE_ID'] = dev_id
cfg['CHANNEL_COUNT'] = int(ch_count)
cfg['CLOCK_RATE'] = int(clock_rate)
cfg['DESTINATION'] = dest
cfg['DB_HOST'] = db_host
cfg['DB_PORT'] = db_port
cfg['DB_USER'] = db_user
cfg['DB_PASSWORD'] = db_pass
cfg['DB_NAME'] = db_name
cfg['DB_DSN'] = f'postgresql://{db_user}:{db_pass}@{db_host}:{db_port}/{db_name}'
cfg['MOCKUP_MODE'] = True if mockup_str.lower() in ('true', '1', 'yes') else False

with open(config_path, 'w') as f:
    json.dump(cfg, f, indent=2)
" "$DAQ_CONFIG_JSON" "$DEVICE_DESCRIPTION" "$DEVICE_ID" "$CHANNEL_COUNT" "$CLOCK_RATE" "$DESTINATION" "$DB_HOST" "$DB_PORT" "$POSTGRES_USER" "$POSTGRES_PASSWORD" "$POSTGRES_DB" "$MOCKUP_MODE" 2>/dev/null || warn "Could not automatically update $DAQ_CONFIG_JSON via python3"
  say "✓ config.json synchronized successfully."
fi
pause "Stage 5 finished. Press Enter to proceed to stack launch and verification."

# ── Stage 6: Stack Launch and Verification ────────────────────────────────
stage "Stack Launch & Service Verification"
say "Deploying the complete IIoT data ingestion stack via Docker Compose."

say "Configuration Summary:"
note "  • Mode        : $([[ "$MOCKUP_MODE" == "true" ]] && echo "MOCKUP (Driverless Simulation)" || echo "REAL HARDWARE (Advantech PCI-1716)")"
note "  • Channels    : $CHANNEL_COUNT ch @ ${CLOCK_RATE} Hz"
note "  • Destination : $DESTINATION"
note "  • Database    : $POSTGRES_DB ($DB_HOST:$DB_PORT, user: $POSTGRES_USER)"

COMPOSE_CMD="$(get_compose_cmd)"

if [[ -n "$COMPOSE_CMD" ]]; then
  if confirm "Start the production stack now ($COMPOSE_CMD up -d)?"; then
    say "Launching containers in detached mode..."
    if $COMPOSE_CMD -f "$PROJECT_ROOT/docker-compose.yml" up -d; then
      say "Waiting for containers to initialize and report healthy..."
      ALL_HEALTHY=false
      for ((i=1; i<=15; i++)); do
        UNHEALTHY="$($COMPOSE_CMD -f "$PROJECT_ROOT/docker-compose.yml" ps 2>/dev/null | grep -iE 'unhealthy|Exit [1-9]' || true)"
        if [[ -z "$UNHEALTHY" ]]; then
          ALL_HEALTHY=true
          break
        fi
        sleep 1
      done

      $COMPOSE_CMD -f "$PROJECT_ROOT/docker-compose.yml" ps

      if [[ "$ALL_HEALTHY" == "true" ]]; then
        say "✓ All containers are operational and healthy."
        say "Service Endpoints:"
        note "  • Ingestion Portal    : http://localhost:8080"
        note "  • Telemetry Plotter   : http://localhost:8084"
        note "  • TimescaleDB         : $DB_HOST:$DB_PORT (DB: $POSTGRES_DB)"
        note "  • Mosquitto MQTT      : localhost:1883"
        note "  • InfluxDB Web UI     : http://localhost:8086"
      else
        warn "Some containers reported unhealthy or exited status."
        say "Troubleshooting: inspect container logs with: $COMPOSE_CMD logs"
      fi
    else
      warn "Failed to bring up Docker Compose stack cleanly."
      say "Troubleshooting & Recovery Steps:"
      step "1. Inspect container logs: $COMPOSE_CMD logs -f daq-navi"
      step "2. Check database container: $COMPOSE_CMD logs timescaledb"
      step "3. Verify port conflicts on host: sudo lsof -i :8080 -i :5432 -i :1883 -i :8086"
      step "4. Ensure Docker daemon is active: sudo systemctl restart docker"
    fi
  else
    note "Stack start skipped. You can manually launch later with: docker compose up -d (or docker-compose up -d)"
  fi
else
  warn "Docker Compose is not available. Please install Docker Compose to start containers (docker compose up -d)."
fi

finish

